### ISSUE TITLE
Dataset file missing

### ISSUE THREAD

**Issue by nanle771** [zhang-tao-whu/vis_clip#1]
I found that the Annotations file is missing compared to the prepared dataset when downloading the YouTube VIS 2021 dataset. Can you help solve this problem? Download link:https://drive.google.com/drive/folders/12DxR2HWTVjULNwKVMdYAvhOmZ9gBxsX2

**Comment by zhang-tao-whu** [comment]
Please refer to [DVIS](https://github.com/zhang-tao-whu/DVIS). If you have any questions, please ask them under [DVIS](https://github.com/zhang-tao-whu/DVIS).
